import ResearchHeader from "@/components/ResearchHeader";
import React from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { contextualSources, externalPrimarySources, primaryCorpusSummary, primaryTextSources, type CorpusDisplaySource } from "@/data/primarySourceGallery";
import { AlertTriangle, ExternalLink, FileSearch, Images, Landmark, ScanText, ShieldCheck, ZoomIn } from "lucide-react";

function PrimaryImageDialog({ item }: { item: CorpusDisplaySource }) {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <button className="group block w-full text-right" aria-label={`فتح ${item.title}`}>
          <article className="flex flex-col overflow-hidden rounded-3xl border border-[#e0d8cb] bg-white text-right shadow-[0_12px_30px_rgba(52,56,43,0.06)] transition duration-200 hover:-translate-y-1 hover:shadow-[0_20px_38px_rgba(52,56,43,0.12)]">
            <div className={`relative overflow-hidden bg-[#1f2922] ${item.wide ? "aspect-[3.3/1]" : "aspect-square"}`}>
              <img src={item.imageUrl} alt={item.alt} className="size-full bg-[#1f2922] object-contain transition duration-500 group-hover:scale-[1.03]" loading="lazy" />
              <div className="absolute inset-0 bg-gradient-to-t from-[#152018]/60 via-transparent to-transparent opacity-70" />
              <span className="absolute bottom-3 left-3 inline-flex size-9 items-center justify-center rounded-full bg-[#fffaf0]/90 text-[#2b4b40] shadow-sm"><ZoomIn className="size-4" /></span>
              <Badge className="absolute right-3 top-3 border-0 bg-[#2b4b40]/95 text-[#fffaf0] hover:bg-[#2b4b40]">{item.corpusRole === "primary-text" ? "نص أولي ظاهر" : "مصدر سياقي"}</Badge>
            </div>
            <div className="flex flex-1 flex-col p-5"><p className="text-[10px] font-semibold tracking-[0.16em] text-[#a56b37]">{item.corpusRole === "primary-text" ? "PRIMARY TEXT" : "CONTEXTUAL SOURCE"} · {item.period}</p><h2 className="mt-2 text-lg font-semibold leading-7 text-[#25352c]">{item.title}</h2><p className="mt-2 text-xs leading-6 text-[#626960]">{item.description}</p><p className="mt-4 rounded-xl bg-[#f5f0e5] px-3 py-2 text-xs leading-6 text-[#665d51]">{item.trainingStatus}</p></div>
          </article>
        </button>
      </DialogTrigger>
      <DialogContent className="max-h-[88vh] w-[min(96vw,1200px)] max-w-[1200px] overflow-hidden border-[#dfd4c3] bg-[#fffdf8] p-0 sm:rounded-3xl" dir="rtl">
        <div className="grid lg:grid-cols-[minmax(0,1.2fr)_minmax(380px,0.8fr)]"><div className="flex h-[min(76vh,680px)] items-center justify-center bg-[#1f2922] p-4 sm:p-6"><img src={item.imageUrl} alt={item.alt} className="max-h-full w-full rounded-2xl object-contain" /></div><div className="max-h-[76vh] overflow-y-auto p-6 sm:p-8"><DialogHeader className="text-right"><p className="text-xs font-semibold tracking-[0.16em] text-[#a56b37]">ORIGINAL TEXT SOURCE · {item.period}</p><DialogTitle className="mt-3 font-serif text-3xl leading-tight text-[#26382e]">{item.title}</DialogTitle><DialogDescription className="mt-3 text-sm leading-7 text-[#666c62]">{item.description}</DialogDescription></DialogHeader><div className="mt-7 space-y-4 text-sm"><div className="rounded-2xl bg-[#f2eee5] p-4"><p className="text-xs font-semibold text-[#81572e]">الحفظ والفهرسة</p><dl className="mt-3 space-y-3 leading-6 text-[#555e54]"><div><dt className="text-xs font-semibold text-[#7f6547]">جهة الحفظ أو المسح</dt><dd>{item.holdingInstitution}</dd></div><div><dt className="text-xs font-semibold text-[#7f6547]">الوصف الفهرسي</dt><dd>{item.catalogueRecord}</dd></div><div><dt className="text-xs font-semibold text-[#7f6547]">جودة الصورة</dt><dd>{item.resolutionNote}</dd></div></dl></div><div className="rounded-2xl border border-[#e4d6bd] bg-[#fff9ee] p-4"><p className="flex items-center gap-2 text-xs font-semibold text-[#81572e]"><ShieldCheck className="size-4" />الحقوق والتدريب</p><p className="mt-2 leading-6 text-[#6c604f]">{item.rights}</p><p className="mt-3 leading-6 text-[#6c604f]">{item.trainingStatus}</p></div><a href={item.sourceUrl} target="_blank" rel="noreferrer" className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#2b4b40] px-4 py-3 text-sm font-semibold text-white transition hover:bg-[#213b32]"><ExternalLink className="size-4" />فتح المصدر الأصلي</a></div></div></div>
      </DialogContent>
    </Dialog>
  );
}

export default function SourceLibrary() {
  return (
    <div className="min-h-screen bg-[#f8f5ef] text-[#2b332b]" dir="rtl">
      <ResearchHeader />
      <main className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">
        <header className="grid gap-8 border-b border-[#ddd4c6] pb-10 lg:grid-cols-[1fr_0.7fr] lg:items-end"><div><p className="text-xs font-semibold tracking-[0.18em] text-[#a56b37]">PRIMARY OLD PERMIC TEXT CORPUS</p><h1 className="mt-3 font-serif text-4xl tracking-tight text-[#24372e] sm:text-5xl">مدوّنة النصوص الأصلية</h1><p className="mt-5 max-w-3xl text-sm leading-8 text-[#62675e]">هذه الصفحة مخصصة للصور التي يظهر فيها نص مكتوب بالبرمية القديمة بالفعل: نقوش أو حواشٍ مخطوطية أو وثائق. لا تعرض جداول الأبجدية أو طبعات الشرح بوصفها بيانات تدريب.</p></div><div className="rounded-3xl border border-[#e5d7bf] bg-[#fff9ee] p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-[#efd7b1] text-[#7f5429]"><Images className="size-5" /></span><div><p className="text-2xl font-semibold text-[#2b4b40]">{primaryCorpusSummary.totalCount}</p><p className="text-xs text-[#756a5c]">مسارات إلى نصوص أصلية موثقة</p></div></div><p className="mt-4 text-xs leading-6 text-[#776854]">{primaryCorpusSummary.hostedCount} صور أولية حرة معروضة هنا، و{primaryCorpusSummary.externalCount} مسارات تفتح فوتوكوبيات مخطوطات أصلية في مصادرها الناشرة لحين تحقق حقوق إعادة الاستضافة.</p></div></header>

	        <section className="mt-10"><div className="mb-6 flex items-center gap-3"><ScanText className="size-5 text-[#a56b37]" /><div><p className="text-xs font-semibold tracking-[0.14em] text-[#a56b37]">HOSTED PRIMARY TEXTS</p><h2 className="mt-1 text-2xl font-semibold">نصوص برمية قديمة ظاهرة داخل التطبيق</h2></div></div><div className="grid items-start gap-6 lg:grid-cols-2">{primaryTextSources.map((item) => <PrimaryImageDialog item={item} key={item.id} />)}</div></section>

        <section className="mt-14 rounded-3xl border border-[#d9d1c3] bg-[#f4f1ea] p-7 sm:p-9"><div className="flex items-start gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-2xl bg-[#e7ddd0] text-[#765a39]"><Landmark className="size-5" /></span><div><p className="text-xs font-semibold tracking-[0.16em] text-[#8c6739]">CONTEXTUAL SOURCES · EXCLUDED FROM CORPUS</p><h2 className="mt-2 text-2xl font-semibold">مصادر سياقية خارج corpus النصوص</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-[#666b62]">هذه الصور توثق الوعاء التاريخي للنقش، لكنها لا تُحتسب ضمن corpus النصوص أو ضمن عينات التدريب لأن النص ليس موضع العرض المباشر فيها.</p></div></div><div className="mt-7 grid gap-5 sm:max-w-md">{contextualSources.map((item) => <PrimaryImageDialog item={item} key={item.id} />)}</div></section>

        <section className="mt-14 rounded-3xl border border-[#e0d7c8] bg-white p-7 sm:p-9"><div className="flex items-start gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-2xl bg-[#edf1e8] text-[#2b4b40]"><FileSearch className="size-5" /></span><div><p className="text-xs font-semibold tracking-[0.16em] text-[#a56b37]">EXTERNAL FACSIMILES · ORIGINAL MANUSCRIPT TEXT</p><h2 className="mt-2 text-2xl font-semibold">فوتوكوبيات مخطوطات أصلية</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-[#666b62]">كل بطاقة تفتح الصفحة أو العارض الذي يحتوي الصورة الأصلية. هذه المواد أقرب إلى ما يصلح لاحقًا للتوسيم، لكنها لا تصبح بيانات تدريب قبل أن يراجع الباحث الحقوق والقراءة وحدود النص داخل الصورة.</p></div></div><div className="mt-7 grid gap-4 lg:grid-cols-2">{externalPrimarySources.map((source) => <article key={source.id} className="rounded-2xl border border-[#e6ded2] bg-[#fffdf9] p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold tracking-[0.13em] text-[#a56b37]">{source.pageReference}</p><h3 className="mt-2 text-lg font-semibold text-[#2c493d]">{source.title}</h3></div><Badge variant="outline" className="border-[#d6c3a7] text-[#85572e]">نص مخطوط أصلي</Badge></div><p className="mt-3 text-sm leading-7 text-[#555f56]">{source.visibleContent}</p><dl className="mt-4 grid gap-3 text-xs leading-6 text-[#70736b]"><div><dt className="font-semibold text-[#4b5a4e]">الوعاء</dt><dd>{source.manuscript}</dd></div><div><dt className="font-semibold text-[#4b5a4e]">الحفظ</dt><dd>{source.location}</dd></div><div><dt className="font-semibold text-[#4b5a4e]">حالة التدريب</dt><dd>{source.trainingStatus}</dd></div></dl><div className="mt-5 rounded-xl bg-[#fff7e9] p-3 text-xs leading-6 text-[#765f45]"><AlertTriangle className="ml-1 inline size-3.5" />{source.rightsNote}</div><a href={source.href} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-[#a56b37] hover:text-[#7e4f24]">فتح فوتوكوبيات النص الأصلي <ExternalLink className="size-4" /></a></article>)}</div></section>

        <section className="mt-12 rounded-3xl border border-dashed border-[#d8cbb8] bg-[#f5f1e8] p-6 text-sm leading-7 text-[#625f57]"><p className="font-semibold text-[#2b4b40]">ما الذي لا يظهر هنا؟</p><p className="mt-2">الطبعات الشارحة وجداول الحروف والتقاويم والمواد التعليمية نُقلت خارج هذه المدوّنة؛ فهي مفيدة لسياق البحث، لكنها ليست صور نصوص أصلية ولا ينبغي استخدامها بوصفها أمثلة OCR للبرمية القديمة.</p><p className="mt-3 font-medium text-[#735936]">{primaryCorpusSummary.trainingBoundary}</p></section>
      </main>
    </div>
  );
}
