import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

describe("synthetic generation notebook", () => {
  it("keeps staged Jupyter cells wired to the real Python generator", () => {
    const notebookPath = new URL("../training/notebooks/old_permic_synthetic_generation.ipynb", import.meta.url);
    const notebook = JSON.parse(readFileSync(notebookPath, "utf8")) as { nbformat: number; cells: Array<{ cell_type: string; source: string[] }> };
    const code = notebook.cells.filter((cell) => cell.cell_type === "code").flatMap((cell) => cell.source).join("\n");
    expect(notebook.nbformat).toBe(4);
    expect(code).toContain("from training.synthetic.generate_old_permic_synthetic import PROFILES, write_dataset");
    expect(code).toContain('"layout": "isolated-glyph"');
    expect(code).toContain('"layout": "ordered-lines"');
    expect(code).toContain('"layout": "structured-pages"');
    expect(code).toContain("from ultralytics import YOLO");
    expect(code).toContain("evaluation_model.val");
    expect(code).toContain('"workers": 6');
    expect(code).toContain("torch.cuda.is_available()");
    expect(code).toContain('"Pillow==11.3.0"');
    expect(code).toContain("import PIL");
    expect(code).toContain("# 9) Snapshot كامل وقابل للاستئناف من GitHub");
    expect(code).toContain("import os");
    expect(code).toContain("FORCE_REGENERATE_DATASET = False");
    expect(code).toContain("TRAINING_PLANS = {");
    expect(code).toContain('"S0": {"epochs": 100, "batch_candidates": (8, 6, 4)');
    expect(code).toContain('"layout": "scattered-glyph"');
    expect(code).toContain('"batch_candidates": (32, 24, 16, 12, 8)');
    expect(code).toContain('"epochs": 60');
    expect(code).toContain("report_gpu_memory");
    expect(code).toContain("torch.cuda.empty_cache()");
    expect(code).toContain("SNAPSHOT_RESTORED_FROM_GITHUB");
    expect(code).toContain("snapshot غير مطابق للمرحلة أو المولد أو الخط");
    expect(code).toContain("ستنشئ المرحلة الحالية بياناتها الحتمية المستقلة");
    expect(code).toContain("SNAPSHOT_REGENERATED_FOR_CURRENT_STAGE");
    expect(code).toContain("سيُعاد توليد {STAGE} حتميًا ثم سيُستبدل snapshotها على GitHub");
    expect(code).toContain("snapshot_matches_training_contract");
    expect(code).toContain("الاحتفاظ ");
    expect(code).toContain("remove_incompatible_training_artifacts");
    expect(code).not.toContain('assert meta.get("identity") == SNAPSHOT_IDENTITY');
    expect(code).toContain("bootstrap_dataset_snapshot()");
    expect(code).toContain("copy_dataset_snapshot");
    expect(code).toContain("PREPARE_REAL_MANUSCRIPT_DATA = False");
    expect(code).toContain("validate_real_labeled_dataset.py");
    expect(code).toContain("RUN_REAL_MANUSCRIPT_FINETUNE = False");
    expect(code).toContain("SYNTHETIC_BASE_EXPERIMENT");
    expect(code).toContain("real_latest.json");
  });

  it("keeps the Colab checkpoint, evaluation, and gated publication workflow explicit", () => {
    const notebookPath = new URL("../training/notebooks/old_permic_synthetic_generation.ipynb", import.meta.url);
    const notebook = JSON.parse(readFileSync(notebookPath, "utf8")) as { cells: Array<{ cell_type: string; source: string[] }> };
    const code = notebook.cells.filter((cell) => cell.cell_type === "code").flatMap((cell) => cell.source).join("\n");
    const prose = notebook.cells.filter((cell) => cell.cell_type === "markdown").flatMap((cell) => cell.source).join("\n");

    expect(code).toContain('"git", "clone"');
    expect(code).toContain('CHECKPOINT_BRANCH = "colab-checkpoints"');
    expect(code).toContain("publish_latest_checkpoint");
    expect(code).toContain("restore_latest_checkpoint_from_github");
    expect(code).toContain("--force-with-lease");
    expect(code).toContain("USE_COLAB_SECRET_FALLBACK = True");
    expect(code).toContain('userdata.get("GITHUB_WRITE_TOKEN")');
    expect(code).toContain("fallback_error");
    expect(code).toContain("تفاصيل Git");
    expect(code).toContain("لم يمس ذلك checkpoint التدريب");
    expect(code).toContain("if repo_publish_dir.exists()");
    expect(code).toContain("sync_latest_checkpoint");
    expect(code).toContain('"--amend", "-m", message');
    expect(code).toContain("assert_resume_is_compatible");
    expect(code).toContain("TRAINING_ALREADY_COMPLETE");
    expect(code).toContain('restored_epoch >= EPOCHS');
    expect(code).toContain("لن يُستدعى resume=True");
    expect(code).toContain('"S0-d1": {');
    expect(code).toContain('"source_branch": "s0-epoch100-checkpoint"');
    expect(code).toContain("prepare_initialization_weight");
    expect(code).toContain("initialization_weight = None if restored_checkpoint else prepare_initialization_weight()");
    expect(code).toContain("warm_start_from_");
    expect(code).toContain("initialization_weight_sha256");
    expect(code).toContain("last_pt_sha256");
    expect(code).toContain("save_period=1");
    expect(code).toContain("dataset_snapshot.json");
    expect(code).toContain("GITHUB_WRITE_TOKEN");
    expect(code).toContain("legacy_checkpoint");
    expect(code).toContain("قُبل اختلاف manifest بعد تحقق الفئات وسجل الأصول وهوية snapshot");
    expect(prose).toContain("لا يحذف `last.pt` أو `resume_state.json`");
    expect(code).toContain("evaluation_model.val");
    expect(code).toContain("release.json");
    expect(code).toContain("PUBLISH_RELEASE = False");
    expect(code).toContain("MAX_GITHUB_WEIGHT_BYTES");
    expect(code).toContain('"latest.json"');
    expect(code).toContain('"publication_status": "published"');
    expect(code).not.toContain("github_read_token");
    expect(code).not.toContain("from google.colab import drive");
    expect(code).not.toContain("restore-public-drive-folder");
    expect(code).not.toContain("RUN_WORKSPACE_BACKUP");
    expect(code).not.toContain("workspace_cache");
    expect(prose).toContain("لا تُرفع");
    expect(prose).toContain("لا يربط الدفتر Google Drive");
    expect(prose).toContain("لا تثبت أداء OCR على مخطوطات تاريخية");
    expect(prose).toContain("لا ينقل هذا الدفتر صور المخطوطات إلى GitHub");
  });
});
